# Generated by Django 4.2.6 on 2023-10-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('genres', models.CharField(max_length=100, verbose_name='Жанри')),
                ('directors', models.CharField(max_length=100, verbose_name='Режисери')),
                ('image', models.CharField(max_length=300, verbose_name='Посилання на зображення')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
            ],
        ),
    ]
