# Generated by Django 4.2.6 on 2023-10-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='imdb_rating',
        ),
    ]
