# Generated by Django 4.2.7 on 2023-12-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_rating_movie_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('price', models.FloatField(verbose_name='Ціна')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Тривалість'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('seat', models.IntegerField(verbose_name='Місце')),
                ('is_free', models.BooleanField(verbose_name='Вільне місце')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session', verbose_name='Сеанс')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='Фільм'),
        ),
    ]
