# Generated by Django 4.2.7 on 2023-12-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_session_movie_duration_ticket_session_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
    ]
