# Generated by Django 4.2.7 on 2023-12-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_ticket_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_free',
        ),
        migrations.AddField(
            model_name='ticket',
            name='isbooked',
            field=models.BooleanField(default=False, verbose_name='Заброньовано'),
        ),
    ]
